/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package app.retera.parsers.mdlx;

import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class MdlxTest {
    @Test void someLibraryMethodReturnsTrue() {
        MdlxModel model = new MdlxModel();
        assertEquals(model.getVersion(), 800);
    }
}
